name: smolishyt

services:
  smolishyt:
    build:
      context: .
    image: smolishyt:latest
    restart: unless-stopped
    init: true
    user: "0:0"
    stop_signal: SIGTERM
    stop_grace_period: 30s
    env_file:
      - ./.env
    environment:
      BINARY_PATH: /usr/local/bin/yt-dlp
      FFMPEG_PATH: /usr/bin/ffmpeg
      FFPROBE_PATH: /usr/bin/ffprobe
      NODE_BINARY_PATH: /usr/bin/node
    command: ["bun", "--env-file=.env", "./dist/channel.js"]
    volumes:
      - type: bind
        source: ./.smolishyt
        target: /app/.smolishyt
